#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://google.com                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Wingman                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : €3.99                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : AIMS app for Flight and Cabin Crew

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Max Morell                             
your_link                                 :                     
your_city                                 :                             
email_address                             : contact.wingmanapp@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Instantly Load Your Roster
    description                           : View your schedule in the way that suits you best—choose between an intuitive overview or the classic horizontal format.
    fontawesome_icon_name                 : calendar
    
  - title                                 : Export to Calendar
    description                           : Seamlessly sync your roster with your preferred calendar app, whether it's iOS, Google, or Outlook.
    fontawesome_icon_name                 : file-export

  - title                                 : Flight Lookup
    description                           : Search for any flight within your airline and see real-time crew assignments for better planning.
    fontawesome_icon_name                 : play-circle

  - title                                 : Compare Rosters
    description                           : Look up colleagues’ rosters and compare schedules side by side.
    fontawesome_icon_name                 : users

  - title                                 : Flight Statistics & FTL Tracking
    description                           : Get an interactive map with up-to-date flight and duty limits (FTLs) to stay compliant and informed.
    fontawesome_icon_name                 : globe
  
  - title                                 : Feature List
    description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : star

  - title                                 : Pay Calculator (Limited Availability) 
    description                           : For select airlines, quickly estimate your variable pay with our built-in calculator.
    fontawesome_icon_name                 : euro


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
